# Generated by Django 2.0.3 on 2018-07-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pizza_type', models.CharField(max_length=64)),
            ],
        ),
        migrations.RenameModel(
            old_name='Toppings',
            new_name='Topping',
        ),
        migrations.RemoveField(
            model_name='pizza',
            name='name',
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pizza',
            name='pizza',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='orders.Type'),
        ),
    ]
