# Generated by Django 2.0.3 on 2018-07-06 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20180706_1417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='price',
        ),
        migrations.RemoveField(
            model_name='topping',
            name='size',
        ),
    ]
