# Generated by Django 2.0.3 on 2018-07-07 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='price',
        ),
    ]
