# Generated by Django 2.0.3 on 2018-07-13 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20180713_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='orders.Pizza'),
        ),
    ]
