# Generated by Django 2.0.3 on 2018-07-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20180713_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pizza_id',
            field=models.IntegerField(default=0),
        ),
    ]
