# Generated by Django 2.0.3 on 2018-07-16 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20180716_1511'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='topping_name',
        ),
    ]
